### ISSUE TITLE
Unable to tell Punch The Clown if my fortune is useful

### ISSUE THREAD

**Issue by madisonsus** [daveklotz/PunchTheClownIssues#2]
To whom it may concern:

After getting a fortune from Punch The Clown it asks me if the fortune was useful.  At present that seems like a rhetorical question as there is no way to give an answer via the screen.  If that is a bug, it needs to be fixed.  If it is a feature to be rhetorical, please ignore.

Regards,
Madison

**Comment by daveklotz** [comment]
Fixed!

**Comment by madisonsus** [comment]
What is the resolution?
